Sprint 2/step 2
Darya1501/react-burger pull request #4
Opened 2022-12-16 23:34 UTC by Darya1501

2022-12-17 02:49 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.js
>    }
**Надо исправить:**

`Tabs` должно быть с маленькой буквы. 

**Можно лучше:**

Лучше вынести в файл `utils/constants.js`

2022-12-17 03:09 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Вы используйте redux;

### **Но есть несколько замечаний, которые нужно исправить:**

- Заказ не должен отправляться если нет булок и ингредиентов.

- В запрос `/orders` должны передаваться обе булки, нужно чтобы булки были в начале и в конце массива.

  https://yadi.sk/d/yctIY8MQ9Rjd0w

- Измените расширение файлов где есть `jsx`, нужно указывать расширение `.jsx`, а не `.js`;

- Создайте папку `app` для компонента `App`.

- Чтобы корректно отрабатывали перехватичики ошибок, в catch у запросов (https://yadi.sk/d/1MzlO-UQCKdqBA), нужно выбрасывать ошибку. `throw new Error("текст ошибки")`.

- Если данных нет, то нужно использовать null, а не пустой объект.

- Поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте.

- Redux:
  - Следует разделить экшены относящиеся к решению конкретной задачи по файлам;
  - Разделите редьюсер на несколько;

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-12-17 03:09 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.js
>    }
**Надо исправить:**

`Tabs` должно быть с маленькой буквы. 

**Можно лучше:**

Лучше вынести в файл `utils/constants.js`

2022-12-17 03:09 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient.js
> +          {item.__v > 0 && (<Counter count={item.__v} size="default" extraClass="m-1" />)}
**Надо исправить:**

поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте

2022-12-17 03:09 UTC, ArslanMustafin commented on src/components/modals/ingredient-details.js
>      <Modal onClose={onClose} header='Детали ингредиента'>
**Надо исправить:**
`IngredienDetails` - это компонент для модального окна, также как и `OrderDetails`.
Не стоит в компоненте для модального окна, использовать самое модальное окно.

Предполагается, что вы будете использовать модальные окна следующим образом: 

```js
<Modal onClose={onClose} header='Детали ингредиента'> 
  <IngredientDetails />
<Modal/>
```

Поправьте также и для компонента `OrderDetails`.

2022-12-17 03:09 UTC, ArslanMustafin commented on src/services/actions/index.js
> +    });
**Надо исправить:**

Здесь и в другом запрос.

Вам также нужно отлавливать ошибку в `.catch`.

2022-12-17 03:09 UTC, ArslanMustafin commented on src/services/reducers/index.js
> +  constructorBun: {},
**Надо исправить:**

Если данных нет, то нужно использовать `null`, а не пустой объект.

2022-12-17 03:09 UTC, ArslanMustafin commented on src/services/reducers/index.js
> +  currentViewedIngredient: {},
**Надо исправить:**

Если данных нет, то нужно использовать `null`, а не пустой объект.

2022-12-17 03:09 UTC, ArslanMustafin commented on src/services/reducers/index.js
> +  order: {},
**Надо исправить:**

Если данных нет, то нужно использовать `null`, а не пустой объект.

2022-12-17 03:09 UTC, ArslanMustafin commented on src/services/reducers/index.js
> +        ingredients: action.items.map((item, index) => index === 0 ? {...item, __v: 2} : item),
**Надо исправить:** 

поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте

2022-12-17 03:09 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +            constructorID: Date.now()
**Надо исправить:**

Редьюсер должен быть чистой функцией, вам нужно генерировать id в функциях `action-creator`.

2022-12-17 03:09 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +        currentViewedIngredient: {}
**Надо исправить:**

Если данных нет, то нужно использовать `null`, а не пустой объект.

2022-12-17 03:09 UTC, ArslanDev666 commented on src/services/actions/index.js
> +import { getIngredients, postOrder } from "../../utils/burger-api";
**Надо исправить:**

Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2022-12-17 03:09 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +import {
**Надо исправить:**

Со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2022-12-18 08:17 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

### **Отметил замечания в коде, рекомендую их исправить:**

2022-12-18 08:17 UTC, ArslanDev666 commented on src/utils/burger-api.js
> +        throw new Error("Success field is not equal")
**Надо исправить:**

Вы меня немного не поняли, вызывать ошибку нужно в catch, чтобы она по цепочке вызовов пошла дальше, а то она остановится на console.error, и редакс не увидит что произошла ошибка.

```js
  const response = await fetch(`${API}/ingredients`)
    .then(checkReponse)
    .then(data => {
      if (data.success) {
        return data.data
      } else {
        Promise.reject("Success field is not equal")
      }
      }).catch(error => { 
        throw new Error(error.message)
      })
```

2022-12-18 08:17 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +  constructorIngredients: [],
**Можно лучше:** 

И в экшенах тоже.

Лучше вынести эти поля в другой редьюсер, который будет отвечать за `constructor`

2022-12-18 08:17 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +          constructorID: Date.now()
**Можно лучше:**

Лучше делать это в action-createor, чтобы каждый раз когда нам нужно будет добавить ингредиент в стейт, не дублировать эту запись.

2022-12-18 08:17 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient.jsx
> +        <Modal onClose={() => dispatch({ type: HIDE_INGREDIENT_DATA })} header='Детали ингредиента'>
**Можно лучше:**

Обработчик событий лучше вынести в отдельную функцию.

2022-12-23 11:14 UTC, merged